functions

diff --git a/.github/workflows/functions.yml b/.github/workflows/functions.yml
--- a/.github/workflows/functions.yml
+++ b/.github/workflows/functions.yml
@@ -16,12 +16,12 @@ jobs:
           ${{ toJSON(github.event.pull_request.labels) }}
           EOF
       - name: Bug step
-        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
+        if: ${{ contains(github.event.pull_request.title, 'fix') }}
         run: echo "I am a bug fix"
       - name: Sleep for 20 seconds
         run: sleep 20
-      - name: Failing step
-        run: exit 1
+#      - name: Failing step
+#        run: exit 1
       - name: I will be skipped
         if: ${{ success() }}
         run: echo "I will print if previous steps succeed."
